In [1]:
import sys
import os

# Define the directory path to the module
ESN_path = os.path.abspath(os.path.join(os.getcwd(), "../EchoStateNetwork-Workshop"))
print(f"Appending {ESN_path} to sys.path")

# Add the directory to sys.path
if ESN_path not in sys.path:
    sys.path.insert(0, ESN_path)

# Validate that the path was added
print("Current sys.path:", sys.path)

# Test the import
try:
    from ESN_class_main import EchoStateNetwork
    print("Successfully imported EchoStateNetwork!")
except ModuleNotFoundError as e:
    print(f"Import failed: {e}")

Appending /home/dafydd/PycharmProjects/py-ESN-software-testing/EchoStateNetwork-Workshop to sys.path
Current sys.path: ['/home/dafydd/PycharmProjects/py-ESN-software-testing/EchoStateNetwork-Workshop', '/home/dafydd/PycharmProjects/py-ESN-software-testing', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '', '/home/dafydd/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages']
Successfully imported EchoStateNetwork!


In [10]:
import numpy as np

# Define parameters for the ESN
ESN_params = {
    'input_dim': 3,       # K: Number of input features
    'nodes': 5,           # N: Number of reservoir nodes
    'output_dim': 2,      # L: Number of output features
    'ridge': 1e-6,        # Ridge regression penalty
    'leak': 0.2,          # Leaking rate
    'connectivity': 0.1,  # Reservoir sparsity
    'input_scaling': np.array([0.5, 1.0, 1.5]),  # Scaling factors for inputs
    'spectral_radius': 0.9,
    'enable_forcing': True,  # Enable feedback
    'seed': 42,
    'bias': 0,
    'teacher_scaling': np.array([1.2, 0.8]),  # Scaling factors for feedback
    'train_length': 500,
    'prediction_length': 50
}

In [12]:
esn = EchoStateNetwork(ESN_params)

# Mock input and feedback data
inputs = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])  # Shape: (K, timesteps)

feedback = np.array([[0.5, 0.6, 0.7],
                     [1.0, 1.1, 1.2]])  # Shape: (L, timesteps)

# Test _scale_inputs
scaled_inputs = esn._scale_inputs(inputs)
print("Scaled Inputs:")
print(scaled_inputs)

# Verify scaling is applied correctly
expected_scaled_inputs = inputs * ESN_params['input_scaling'][:, None]
assert np.allclose(scaled_inputs, expected_scaled_inputs), "Input scaling failed!"

# Test _scale_feedback
scaled_feedback = esn._scale_feedback(feedback)
print("Scaled Feedback:")
print(scaled_feedback)

# Verify scaling is applied correctly
expected_scaled_feedback = feedback * ESN_params['teacher_scaling'][:, None]
assert np.allclose(scaled_feedback, expected_scaled_feedback), "Feedback scaling failed!"

print("All tests passed!")

Scaled Inputs:
[[ 0.5  1.   1.5]
 [ 4.   5.   6. ]
 [10.5 12.  13.5]]
Scaled Feedback:
[[0.6  0.72 0.84]
 [0.8  0.88 0.96]]
All tests passed!
